name: Build and Test

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches: [ main ]

jobs:
  general:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installation (Poetry/Dependencies)
        run: |
          pip install poetry
          poetry install --no-dev

      - name: Tests (Pytest)
        run: |
          pytest tests/

      - name: Build and publish to PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/* --username=ngm1450 --password=14508419Na*


    
          
