name: Build and Test

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build (Poetry)
        run: |
          pip install poetry
          poetry install --no-dev

      - name: Tests (Pytest and Poetry)
        run: |
          poetry run pytest
