name: Build and Test

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches: [ main ]

jobs:
  tests-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installation (Poetry/Dependencies)
        run: |
          curl -sSL https://install.python-poetry.org | python3.8 -
          poetry install

      - name: Tests (Pytest)
        run: |
          poetry run pytest tests/

      - name: Build and publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
          poetry build 
          poetry publish    

     



    
          
